"""add api-compatible fields

Revision ID: 9b160a30bfbf
Revises: da563baec9a3
Create Date: 2026-04-12 22:14:43.292340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b160a30bfbf'
down_revision: Union[str, Sequence[str], None] = 'da563baec9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('reorder_level', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('warehouse_id', sa.String(length=64), nullable=False))
    op.add_column('purchase_orders', sa.Column('vendor_id', sa.String(length=64), nullable=False))
    op.add_column('purchase_orders', sa.Column('product_id', sa.String(length=64), nullable=False))
    op.add_column('purchase_orders', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('purchase_orders', sa.Column('created_date', sa.Date(), nullable=True))
    op.add_column('shipments', sa.Column('product_id', sa.String(length=64), nullable=False))
    op.add_column('shipments', sa.Column('warehouse_id', sa.String(length=64), nullable=False))
    op.add_column('shipments', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('shipments', sa.Column('received_date', sa.Date(), nullable=True))
    op.add_column('vendors', sa.Column('contact_person', sa.String(length=200), nullable=False))
    op.add_column('warehouses', sa.Column('current_usage', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'current_usage')
    op.drop_column('vendors', 'contact_person')
    op.drop_column('shipments', 'received_date')
    op.drop_column('shipments', 'quantity')
    op.drop_column('shipments', 'warehouse_id')
    op.drop_column('shipments', 'product_id')
    op.drop_column('purchase_orders', 'created_date')
    op.drop_column('purchase_orders', 'quantity')
    op.drop_column('purchase_orders', 'product_id')
    op.drop_column('purchase_orders', 'vendor_id')
    op.drop_column('products', 'warehouse_id')
    op.drop_column('products', 'reorder_level')
    op.drop_column('products', 'price')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
